set(CPACK_PACKAGE_VENDER "tonghao.yuan")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "modern cmake tricks")
set(CPACK_PACKAGE_VERSION ${version})
set(CPACK_PACKAGE_HOMEPAGE_URL ${PROJECT_HOMEPAGE_URL})
set(CPACK_PACKAGE_CONTACT "yuantonghao@gmail.com")
set(CPACK_PACKAGE_NAME "${PROJECT_NAME}")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "${PROJECT_NAME}")
set(CPACK_PACKAGE_EXECUTABLES ${PROJECT_NAME} "${PROJECT_NAME}")
set(CPACK_CREATE_DESKTOP_LINKS ${PROJECT_NAME})

include(InstallRequiredSystemLibraries)

set(CPACK_GENERATOR WIX ZIP)

# set(CPACK_WIX_PRODUCT_ICON "${CMAKE_SOURCE_DIR}/assets/logo_150.ico")
set(CPACK_WIX_LIGHT_EXTRA_FLAGS "-dcl:high")

include(CPack)